# Generated by Django 5.0.6 on 2024-06-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_testimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='image',
        ),
        migrations.RemoveField(
            model_name='test',
            name='points',
        ),
        migrations.RemoveField(
            model_name='test',
            name='rectangles',
        ),
    ]
