# Generated by Django 5.0.6 on 2024-06-15 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_testimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='testers',
            field=models.ManyToManyField(related_name='assigned_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
