# Generated by Django 5.0.6 on 2024-06-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
    ]
