# Generated by Django 5.0.6 on 2024-06-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='Unnamed Test', max_length=255),
        ),
    ]
