# Generated by Django 5.0.6 on 2024-06-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_testresult_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='duration',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
