# Generated by Django 5.0.6 on 2024-08-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_avatar_customuser_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
